### ISSUE TITLE
无法使用CUDA

### ISSUE THREAD

**Issue by tanzeyy** [wulivicte/crnn#5]
在编译安装warp_ctc的时候设置了CUDA_HOME，运行时依然提示no CUDA-capable device is detected
torch.cuda.is_available() 返回true

**Comment by YoungMiao** [comment]
可以把错误的截图贴出来吗？ @tanzeyy

**Comment by tanzeyy** [comment]
@YoungMiao 
运行：
```
python crnn_main.py --trainroot ~/plates/train_lmdb --valroot ~/plates/val_lmdb --nh 128 --cuda --random_sample
```

出现：
```
Namespace(Diters=5, adadelta=False, adam=False, alphabet='0123456789ABCDEFGHJKLMNPQRSTUVWXYZ\xe4\xba\xac\xe6\xb2\xaa\xe6\xb4\xa5\xe6\xb8\x9d\xe5\x86\x80\xe6\x99\x8b\xe8\x92\x99\xe8\xbe\xbd\xe5\x90\x89\xe9\xbb\x91\xe8\x8b\x8f\xe6\xb5\x99\xe7\x9a\x96\xe9\x97\xbd\xe8\xb5\xa3\xe9\xb2\x81\xe8\xb1\xab\xe9\x84\x82\xe6\xb9\x98\xe7\xb2\xa4\xe6\xa1\x82\xe7\x90\xbc\xe5\xb7\x9d\xe8\xb4\xb5\xe4\xba\x91\xe8\x97\x8f\xe9\x99\x95\xe7\x94\x98\xe9\x9d\x92\xe5\xae\x81\xe6\x96\xb0\xe6\xb8\xaf\xe5\xad\xa6\xe4\xbd\xbf\xe8\xad\xa6\xe6\xbe\xb3\xe6\x8c\x82\xe5\x86\x9b\xe5\x8c\x97\xe5\x8d\x97\xe5\xb9\xbf\xe6\xb2\x88\xe5\x85\xb0\xe6\x88\x90\xe6\xb5\x8e\xe6\xb5\xb7\xe6\xb0\x91\xe8\x88\xaa\xe7\xa9\xba', batchSize=64, beta1=0.5, crnn='', cuda=True, displayInterval=500, experiment=None, imgH=32, imgW=100, keep_ratio=False, lr=0.01, n_test_disp=10, ngpu=1, nh=128, niter=1000, random_sample=True, saveInterval=500, trainroot='/home/jushitech/plates/train_lmdb', valInterval=500, valroot='/home/jushitech/plates/val_lmdb', workers=2)
Random Seed:  2453
CRNN(
  (cnn): Sequential(
    (conv0): Conv2d(1, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (relu0): ReLU(inplace)
    (pooling0): MaxPool2d(kernel_size=(2, 2), stride=(2, 2), dilation=(1, 1), ceil_mode=False)
    (conv1): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (relu1): ReLU(inplace)
    (pooling1): MaxPool2d(kernel_size=(2, 2), stride=(2, 2), dilation=(1, 1), ceil_mode=False)
    (conv2): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (batchnorm2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (relu2): ReLU(inplace)
    (conv3): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (relu3): ReLU(inplace)
    (pooling2): MaxPool2d(kernel_size=(2, 2), stride=(2, 1), padding=(0, 1), dilation=(1, 1), ceil_mode=False)
    (conv4): Conv2d(256, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (batchnorm4): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (relu4): ReLU(inplace)
    (conv5): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (relu5): ReLU(inplace)
    (pooling3): MaxPool2d(kernel_size=(2, 2), stride=(2, 1), padding=(0, 1), dilation=(1, 1), ceil_mode=False)
    (conv6): Conv2d(512, 512, kernel_size=(2, 2), stride=(1, 1))
    (batchnorm6): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (relu6): ReLU(inplace)
  )
  (rnn): Sequential(
    (0): BidirectionalLSTM(
      (rnn): LSTM(512, 128, bidirectional=True)
      (embedding): Linear(in_features=256, out_features=128, bias=True)
    )
    (1): BidirectionalLSTM(
      (rnn): LSTM(128, 128, bidirectional=True)
      (embedding): Linear(in_features=256, out_features=84, bias=True)
    )
  )
)
THCudaCheck FAIL file=/home/jushitech/pytorch/aten/src/THC/THCGeneral.cpp line=70 error=38 : no CUDA-capable device is detected
Traceback (most recent call last):
  File "crnn_main.py", line 124, in <module>
    crnn.cuda()
  File "/home/jushitech/anaconda2/envs/crnn/lib/python2.7/site-packages/torch/nn/modules/module.py", line 230, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/jushitech/anaconda2/envs/crnn/lib/python2.7/site-packages/torch/nn/modules/module.py", line 152, in _apply
    module._apply(fn)
  File "/home/jushitech/anaconda2/envs/crnn/lib/python2.7/site-packages/torch/nn/modules/module.py", line 152, in _apply
    module._apply(fn)
  File "/home/jushitech/anaconda2/envs/crnn/lib/python2.7/site-packages/torch/nn/modules/module.py", line 158, in _apply
    param.data = fn(param.data)
  File "/home/jushitech/anaconda2/envs/crnn/lib/python2.7/site-packages/torch/nn/modules/module.py", line 230, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: cuda runtime error (38) : no CUDA-capable device is detected at /home/jushitech/pytorch/aten/src/THC/THCGeneral.cpp:70
```

**Comment by YoungMiao** [comment]
@tanzeyy 我给你几个建议：1、确保gpu没有被占用；2、正确安装wrap_ctc（你报的这个错误极有可能是未检测到cuda）
`GPU版在环境变量中添加 export CUDA_HOME="/usr/local/cuda"
cd pytorch_binding
python setup.py install`

**Comment by tanzeyy** [comment]
@YoungMiao GPU无占用，wrap_ctc已按照tutorial正确安装

**Comment by Dinghow** [comment]
I’ve met the same problem, @tanzeyy Did you solve this problem？
